{{- if .Values.api.readinessProbe.exec -}}
{{ fail "Your values are still using the old readinessProbe values, this will no longer work as expected" }}
{{- end -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "funkwhale.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "funkwhale.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    audio.funkwhale/component: app
    helm.sh/chart: {{ include "funkwhale.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "funkwhale.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      audio.funkwhale/component: app
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "funkwhale.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        audio.funkwhale/component: app
    spec:
      containers:
        - name: funkwhale
          image: {{ include "funkwhale.imageUri" (dict "Scope" .Values.api.image "Values" .Values "Chart" .Chart) | quote }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy | default .Values.image.pullPolicy }}
          readinessProbe:
            {{ toYaml .Values.api.readinessProbe | nindent 12 }}
          livenessProbe:
            {{ toYaml .Values.api.livenessProbe | nindent 12 }}
          startupProbe:
            {{ toYaml .Values.api.startupProbe | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "funkwhale.fullname" . }}
          - secretRef:
              name: {{ include "funkwhale.fullname" . }}
          volumeMounts:
            - name: static
              mountPath: /srv/funkwhale/data/static/
            - name: data
              mountPath: /srv/funkwhale/data
{{- with .Values.api.extraVolumeMounts }}
            {{ toYaml . | nindent 12 }}
{{- end }}
          ports:
            - name: api
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
        - name: nginx
          image: {{ include "funkwhale.imageUri" (dict "Scope" .Values.front.image "Values" .Values "Chart" .Chart) | quote }}
          imagePullPolicy: {{ .Values.front.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: FUNKWHALE_API_HOST
              value: localhost
            - name: FUNKWHALE_API_PORT
              value: '5000'
          envFrom:
          - configMapRef:
              name: {{ include "funkwhale.fullname" . }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            {{ toYaml .Values.front.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ toYaml .Values.front.readinessProbe | nindent 12 }}
          startupProbe:
            {{ toYaml .Values.front.startupProbe | nindent 12 }}
          volumeMounts:
            - mountPath: /srv/funkwhale/data
              name: data
            - mountPath: /usr/share/nginx/html/staticfiles
              name: static
              readOnly: true
{{- if .Values.front.extraVolumeMounts }}
{{ toYaml .Values.front.extraVolumeMounts | indent 12 }}
{{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: static
          emptyDir: {}
        - name: data
    {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "funkwhale.fullname" .) }}
    {{- else }}
          emptyDir: {}
    {{- end }}
{{- if .Values.api.extraVolumes }}
{{ toYaml .Values.api.extraVolumes | indent 8 }}
{{- end }}
