---
apiVersion: v2
name: element-web
description: |
  All-in-one secure chat app for teams, friends and organisations.
  Keeps conversations in your control, safe from data-mining and ads.
  Talk to everyone through the open global Matrix network, protected by proper
  end-to-end encryption.
icon: https://element.io/images/logo-mark-primary.svg
appVersion: 1.12.7

type: application
version: 1.4.27

maintainers:
  - name: Alexander Olofsson
    email: ace@haxalot.com
