---
apiVersion: v2
name: synatainer
description: Synapse Maintenance Container
home: https://gitlab.com/mb-saces/synatainer
type: application

version: 1.1.2
appVersion: 0.4.2

maintainers:
  - name: Alexander Olofsson
    email: ace@haxalot.com
