---
apiVersion: v2
name: sliding-sync-proxy
description: An implementation of MSC3575
appVersion: "0.99.6"

type: application
version: 0.2.0
maintainers:
  - name: Alexander Olofsson
    email: ace@haxalot.com

dependencies:
  - name: postgresql
    version: ^12.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
