---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-scripts
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/*.sh").AsConfig | indent 2 }}
